name: Reproducibility
on:
  push:
    paths-ignore:
      - reproduced.svg

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if last commit was from github-actions bot
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "Last commit author: $AUTHOR"
          if [ "$AUTHOR" = "github-actions[bot]" ]; then
           echo "Commit made by github-actions bot. Exiting."
           exit 0
          fi
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install reproducibleRchunks
        run: R -e "install.packages(c(\"reproducibleRchunks\", \"sentimentr\", \"renv\"))"
      - name: Run reproducibility checks
        run: |
          Rscript - <<'EOF'
          library(reproducibleRchunks)
          renv::restore()
          files <- list.files(pattern = '\\.[Rr]md$', recursive = TRUE)
          success <- all(sapply(files, isReproducible))
          if (success) {
            download.file('https://img.shields.io/badge/reproduced-brightgreen.svg', 'reproduced.svg', mode = 'wb')
          } else {
            download.file('https://img.shields.io/badge/reproduced-failing-red.svg', 'reproduced.svg', mode = 'wb')
          }
          EOF
      - uses: actions/upload-artifact@v4
        with:
          name: reproduced-badge
          path: reproduced.svg
      - name: Commit and push
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reproduced.svg
          git commit -m "chore: add generated file" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
