name: Reproducibility
on:
  push:
    paths-ignore:
      - reproduced.svg

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    container:
        image: rocker/verse:latest
    steps:
      - name: Install packages
        run: Rscript -e "install.packages(c(\"reproducibleRchunks\", \"renv\"))"
#      - name: Install reproducibleRchunks from github
#        run: Rscript -e "remotes::install_github('brandmaier/reproducibleRchunks')"
#      - name: Install reproducibleRchunks from github
#        run: |
#          Rscript - <<'EOF'
#          Sys.setenv(GITHUB_PAT = Sys.getenv('GITHUB_TOKEN'))
#          remotes::install_github('brandmaier/reproducibleRchunks')
#          EOF
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Check if last commit was from github-actions bot
        run: |
          git config --global --add safe.directory /__w/reproducibleRchunks-renv-demo/reproducibleRchunks-renv-demo
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "Last commit author: $AUTHOR"
          if [ "$AUTHOR" = "github-actions[bot]" ]; then
           echo "Commit made by github-actions bot. Exiting."
           exit 0
          fi
      - name: Installation within renv
        run: |
          Rscript - <<'EOF'
          renv::restore()
          install.packages("reproducibleRchunks_1.2.0.tar.gz", repos = NULL, type = "source")
          EOF
      - name: Run reproducibility checks
        run: |
          Rscript - <<'EOF'
          renv::restore()
          library(reproducibleRchunks)
          files <- list.files(pattern = '\\.[Rr]md$', recursive = TRUE)
          success <- all(sapply(files, isReproducible))
          if (is.na(success)) {
            download.file('https://img.shields.io/badge/reproducibility_status-unknown-black.svg', 'reproduced.svg', mode = 'wb')
          } else if (success) {
            download.file('https://img.shields.io/badge/reproduced-brightgreen.svg', 'reproduced.svg', mode = 'wb')
          } else {
            download.file('https://img.shields.io/badge/reproduced-failing-red.svg', 'reproduced.svg', mode = 'wb')
          }
          EOF
      - uses: actions/upload-artifact@v4
        with:
          name: reproduced-badge
          path: reproduced.svg
      - name: Commit and push
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reproduced.svg
          git commit -m "chore: add generated file" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
